### ISSUE TITLE
Connection to Strava does not work

### ISSUE THREAD

**Issue by msgen** [chadj/gpedal#4]
This is the answer from the oauth when trying to connect to Strava:

{
    "message": "Bad Request",
    "errors": [
        {
            "resource": "Authorize",
            "field": "scope",
            "code": "invalid"
        }
    ]
}

The fix is simple: in the ui.js (line 214) you have to change the scope=write to scope=activity:write according to: https://developers.strava.com/docs/authentication/

**Comment by chadj** [comment]
I'll get this fixed tomorrow!

**Comment by chadj** [comment]
Fixed now - you may have to do a force reload on that page to clear the old version of the js from your browser cache.

**Comment by msgen** [comment]
Thanks! On Dec 11, 2019 8:00 PM, Chad Johnson <notifications@github.com> wrote:Fixed now - you may have to do a force reload on that page to clear the old version of the js from your browser cache.
