### ISSUE TITLE
Google API Pricing

### ISSUE THREAD

**Issue by JPhilC** [chadj/gpedal#43]
Hi Chad,

Not so much an issue but a question.

This Repo was brought to my attention when I posted in a Facebook group about a similar project I have recently started working on. The stinger for me is the cost of using the Static Street View API. I noticed that you are using the Javascript API so I looked into that too as I wondered if it was free. It turns out to be even more expensive (per call) than the API I am using so my question is how are you able to make the application available for general use? Or have you found a way of stopping it when the calls are approaching the $200/mth allowance you get from Google.

Kind regards,

Phil

**Comment by chadj** [comment]
Fair question.  GPedal stays within the free usage limit.  I have nothing in place to stop it from going over those limits.  If I did see a spike in usage I would take it down.

**Comment by JPhilC** [comment]
Hi, 

Thanks for answering so quickly. I'll try the same approach.

Phil.
