### ISSUE TITLE
Speed vs cadence / hill grades

### ISSUE THREAD

**Issue by smokedsalmonbagel** [chadj/gpedal#5]
Firstly - thanks so much @chadj - This is an awesome project!

I was thinking about implementing feedback to my trainer (roadbike on stand) with some custom hardware.  I was planning to output the hill-grade to a bluetooth serial device, or possibly just to a http server to turn a step motor. I can probably manage this but I had a question about speed vs cadence. I have both meters but as I understand the application currently only looks at cadence, from which it derives speed and power?  

Javascript is not my strong suit but I am going to try to see if I can flip things around so speed is the driven variable.   Just want to make sure this approach makes sense.  I also considered whether it would be easier to hack this by using speed as cadence with some scaling.

**Comment by smokedsalmonbagel** [comment]
I am a bit confused between speed and cadence - today the cadence magnet was not lined up and it seemed to use the speed only (no RPMs were displayed).  Is this the expected behavior?  If so it should solve the first part of my problem - just disable cadence.

**Comment by chadj** [comment]
A little back story here.  GPedal was primarily written to be driven by Bluetooth power meters (not cadence and speed sensors). I recently wedged in the ability to derive a power value from only a speed sensor assuming you were riding on a Cyclops Magneto dumb trainer. To pull that off I used data from these blog posts: https://machiine.com/2018/how-accurate-is-zwifts-power-estimate-for-classic-trainers/ . This is similar to how Zwift handles dumb trainers. But I only have a power curve for the one trainer v.s. the hundreds that Zwift supports.  GPedal's support for reading in speed data (not cadence) is a little incomplete right now.

So if you're using the "Cycleops Magneto Power Curve" Power Meter then what you're seeing is correct.  It will try to read in speed data to derive a power value.  The cadence value is only used for display purposes.  I wedged in the ability to read in speed values from cadence sensors that broadcast both data points.  Which was a quick hack for sure.

Does that help explain the situation ?

**Comment by smokedsalmonbagel** [comment]
That helps a lot.  I am not looking for the power reading to be exact - more that a higher gear translates to a faster speed.  I think this will work.  I will continue looking into methods for adjusting the resistance for hills.  It sounds like there are at least a few others interested in that,

**Comment by chadj** [comment]
If you don't mind me asking which trainer are you on?  I might be able to put together a power curve for it.

**Comment by smokedsalmonbagel** [comment]
Sure, that would be great - it is a[ Sportneer Bike Trainer ](https://www.amazon.com/gp/product/B071HQFKBY/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1).  It has a resistance setting so I am not sure how that factors in.  I am also using the [Wahoo Speed / Cadence sensor](https://www.amazon.com/Wahoo-Speed-Cadence-Sensor-Bluetooth/dp/B00NW882KM) which works great with the application.

**Comment by chadj** [comment]
Ok, I checked online ( google 😊 ) and I couldn't find any power curve/data available for this trainer.   So we're out of luck.
